### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by alexjwebb1** [cedadev/wflogger#11]
I can run the code up until:
df = pd.read_sql(query, pg_url)

where I get the error:

OperationalError: (psycopg2.OperationalError) FATAL:  password authentication failed for user "jasmin_workflows"
(Background on this error at: https://sqlalche.me/e/14/e3q8)

This puzzles me because in creds_dict is says my user is 'aw438' as i'd expect, and that the 'dbname' is jasmin_workflows.

**Comment by agstephens** [comment]
Hi @alexjwebb1, thanks for trying it out. I have updated the notebook example and this is now the recommended notebook:

https://github.com/cedadev/wflogger/blob/main/notebooks/wflog-plots.ipynb

Please try that and see if you get the same error. Note that this will only work if you are viewing the notebook through the JASMIN Notebook Service at:

https://notebooks.jasmin.ac.uk/

**Comment by alexjwebb1** [comment]
Hi Ag,
I've pulled the repository and i've tried running it through the notebook service and I get the same error when running [3]

It's a very long error message but here's the important bit: (it broke on the df1 call.)
OperationalError: (psycopg2.OperationalError) FATAL:  password authentication failed for user "jasmin_workflows"
(Background on this error at: https://sqlalche.me/e/14/e3q8)

**Comment by agstephens** [comment]
Sorry @alexjwebb1, it was a bug in the code. I had accidentally used the db name as the user in the credentials URL for postgres. It worked for me because the two are the same. I have pushed the change to the `main` branch on github. Please try again.
